Add Andy header and empty lines at the end
cse1110/andy-maven-plugin pull request #3
Opened 2021-09-26 21:05 UTC by martinmladenov

Added the following header before the code that runs Andy:
```
            */(##%#*.
            //**(/////(/*/*/.
         ,/*****,,,,,,,,,,***/#(
       ,#***,,,,,,,,,,,,,*,***//%
       (/***,,,.......,,,,,,**//(
       %/***,,............,,,*///(
       (#****,,.........,*##/,/(/(
       (((*,**,,(,(/*..,#/*%#/#//###
      **#/**,,,,,***,,,,/*,,,*,,/#((
     ,,,,/***,.....,,*.,*(*,,,,*/((
       ,,.,(**,...*,*/,,(%#/***#(#/
         ,,/#/**//*,**.(*///(#*/(.
           /(/**,*/#.. . ,*//*,##
            *(((/,..,,,,*/#**.%(
         %&*/*#,(#,....,,,,,,,#
        %%%%%////&%*.**.*,**(@@&%#
       %%#%%%%%#//*/%&&&%&%(#@@&&&%(%&%/
    #%%%%%%%%%%%%%///**/(#&#&@@@&%%%@/%&
 ##%%%%%%%%%%%%%%%&&%//*/%@@(@&%#@@@%&&& 
#########################################
#                                       #
#                A N D Y                #
#                                       #
#########################################
```

Also, added a few extra lines after the Andy output and at the end.

2021-09-27 01:49 UTC, mauricioaniche requested changes
Minor change

2021-09-27 01:49 UTC, mauricioaniche commented on src/main/java/com/github/cse1110/andy/AndyMojo.java
> +        System.out.println(
Extract this to a method printHeader() or something

2021-09-27 01:52 UTC, mauricioaniche commented
Also, I was thinking more of just writing "Andy" in three or four lines, like other console apps do. I feel the full ascii art is a bit too big.

2021-09-27 07:20 UTC, martinmladenov commented
Should I keep the rectangle with the Andy text and remove everything above it like this?

```
#########################################
#                                       #
#                A N D Y                #
#                                       #
#########################################
```

2021-09-29 06:01 UTC, mauricioaniche commented
I was thinking of something like this: http://www.patorjk.com/software/taag/#p=display&f=Doom&t=Andy

WDYT?

2021-09-29 09:56 UTC, martinmladenov commented
I agree, this one is better! I'll change it in the code.

2021-09-29 18:24 UTC, martinmladenov commented
What do you think about those styles:
Big:
```
                     _       
     /\             | |      
    /  \   _ __   __| |_   _ 
   / /\ \ | '_ \ / _` | | | |
  / ____ \| | | | (_| | |_| |
 /_/    \_\_| |_|\__,_|\__, |
                        __/ |
                       |___/ 
```
Doom (the one you suggested):
```
  ___            _       
 / _ \          | |      
/ /_\ \_ __   __| |_   _ 
|  _  | '_ \ / _` | | | |
| | | | | | | (_| | |_| |
\_| |_/_| |_|\__,_|\__, |
                    __/ |
                   |___/ 
```
Standard:
```
     _              _       
    / \   _ __   __| |_   _ 
   / _ \ | '_ \ / _` | | | |
  / ___ \| | | | (_| | |_| |
 /_/   \_\_| |_|\__,_|\__, |
                      |___/ 
```
Star Wars:
```
     ___      .__   __.  _______  ____    ____ 
    /   \     |  \ |  | |       \ \   \  /   / 
   /  ^  \    |   \|  | |  .--.  | \   \/   /  
  /  /_\  \   |  . `  | |  |  |  |  \_    _/   
 /  _____  \  |  |\   | |  '--'  |    |  |     
/__/     \__\ |__| \__| |_______/     |__|     
```
Roman:
```
      .o.                         .o8              
     .888.                       "888              
    .8"888.     ooo. .oo.    .oooo888  oooo    ooo 
   .8' `888.    `888P"Y88b  d88' `888   `88.  .8'  
  .88ooo8888.    888   888  888   888    `88..8'   
 .8'     `888.   888   888  888   888     `888'    
o88o     o8888o o888o o888o `Y8bod88P"     .8'     
                                       .o..P'      
                                       `Y8P'       
                                                   
```
Univers:
```
                                                         
       db                               88               
      d88b                              88               
     d8'`8b                             88               
    d8'  `8b      8b,dPPYba,    ,adPPYb,88  8b       d8  
   d8YaaaaY8b     88P'   `"8a  a8"    `Y88  `8b     d8'  
  d8""""""""8b    88       88  8b       88   `8b   d8'   
 d8'        `8b   88       88  "8a,   ,d88    `8b,d8'    
d8'          `8b  88       88   `"8bbdP"Y8      Y88'     
                                                d8'      
                                               d8'       
```

I personally like either Big or Standard more than Doom. What do you think?

2021-10-01 18:56 UTC, mauricioaniche commented
the first three! You can pick!

2021-10-02 17:30 UTC, merged